# Generated by Django 5.2.7 on 2025-10-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_task_category"),
        ("subtasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="subTasks",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="subtasks.subtask"
            ),
        ),
    ]
