# Generated by Django 5.2.7 on 2025-10-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_task_subtasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="subTasks",
        ),
    ]
