# Generated by Django 5.2.7 on 2025-10-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_task_subtasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("user", "User"),
                    ("moderator", "Moderator"),
                    ("guest", "Guest"),
                    ("editor", "Editor"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
